# Generated by Django 3.2.2 on 2022-02-19 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordo', '0002_publicchatroom_publicchatmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicchatroom',
            name='users',
        ),
        migrations.DeleteModel(
            name='PublicChatMessage',
        ),
        migrations.DeleteModel(
            name='PublicChatRoom',
        ),
    ]
