# Generated by Django 3.2.2 on 2022-02-21 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordo', '0004_message_room'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
