# Generated by Django 3.2.2 on 2022-02-23 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordo', '0006_chat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
