# Generated by Django 3.2.2 on 2022-02-24 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordo', '0008_message_room'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ordo',
        ),
    ]
