# Generated by Django 3.2.2 on 2022-02-26 11:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordo', '0009_delete_ordo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.TimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
