# Generated by Django 3.2.2 on 2022-03-01 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordo', '0010_alter_message_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateField(default=True),
        ),
    ]
