# Generated by Django 3.2.2 on 2022-03-01 18:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordo', '0011_alter_message_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
