# Generated by Django 3.2.2 on 2022-03-02 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordo', '0012_alter_message_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upcoming_meetings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=False, max_length=25, verbose_name='Заголовок')),
                ('description', models.TextField(default=False, verbose_name='Краткое описание')),
                ('image', models.ImageField(default=False, upload_to='')),
            ],
        ),
    ]
