# Generated by Django 3.2.2 on 2022-03-02 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordo', '0014_alter_upcoming_meetings_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcoming_meetings',
            name='description',
            field=models.TextField(default=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='upcoming_meetings',
            name='image',
            field=models.ImageField(default=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='upcoming_meetings',
            name='title',
            field=models.CharField(default=True, max_length=25, verbose_name='Заголовок'),
        ),
    ]
