# Generated by Django 3.2.2 on 2022-03-02 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordo', '0015_auto_20220302_0905'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Upcoming_meetings',
            new_name='Product',
        ),
    ]
