# Generated by Django 3.2.2 on 2022-03-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordo', '0016_rename_upcoming_meetings_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='no-image.jpg', upload_to=''),
        ),
    ]
