# Generated by Django 3.2.2 on 2022-03-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordo', '0018_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default=False, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='no-image.jpg', upload_to='images_default'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(default=False, max_length=25, verbose_name='Заголовок'),
        ),
    ]
