# Generated by Django 3.2.2 on 2022-03-03 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordo', '0020_alter_product_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Meetings',
        ),
    ]
