# Generated by Django 3.2.2 on 2022-03-03 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordo', '0021_rename_product_meetings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meetings',
            options={'verbose_name_plural': 'Встречи'},
        ),
    ]
