# Generated by Django 3.2.2 on 2022-03-03 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordo', '0022_alter_meetings_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetings',
            name='title',
            field=models.CharField(default=False, max_length=30, verbose_name='Заголовок'),
        ),
    ]
