# Generated by Django 3.2.2 on 2022-03-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordo', '0024_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='comment',
            field=models.CharField(max_length=255),
        ),
    ]
