# Generated by Django 3.2.2 on 2022-03-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordo', '0026_auto_20220304_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=False)),
                ('image', models.ImageField(default=False, upload_to='')),
                ('time', models.DateTimeField(default=False)),
                ('title', models.CharField(default=False, max_length=100)),
                ('text', models.TextField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Встречи',
            },
        ),
        migrations.AlterModelOptions(
            name='meetings',
            options={'verbose_name_plural': 'События'},
        ),
    ]
