# Generated by Django 3.2.2 on 2022-03-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordo', '0027_auto_20220304_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meets',
            name='time',
            field=models.TimeField(default=False),
        ),
    ]
